/*
 * ResourceManager.java
 *
 * Created on 2009年9月23日, 下午5:20
 */

package it.businesslogic.ireport.plugin.filemanager;

import it.businesslogic.ireport.gui.MainFrame;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JOptionPane;

import com.chinacreator.ireport.AddedOperator;
import com.chinacreator.ireport.IreportConstant;
import com.chinacreator.ireport.IreportUtil;
import com.chinacreator.ireport.component.DialogFactory;

/**
 *
 * @author  Administrator
 */
public class ResourceManager extends javax.swing.JDialog {
    
    /** Creates new form ResourceManager */
	
	private String homepath = System.getProperty("user.home")+File.separator+".ireport"+File.separator;
    public ResourceManager(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("报表临时文件目录"));

        jLabel1.setText("目录位置");

        jButton1.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/filemanager/folder_open.gif"))); // NOI18N
        jButton1.setText("打开文件夹");

        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        
        
        jButton2.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/filemanager/delfile.gif"))); // NOI18N
        jButton2.setText("清理文件夹");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        
        jTextField3.setEditable(false);
        jTextField3.setText(new File(homepath+"remoteFiles").getPath());
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 11, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("模板文件目录"));

        jLabel4.setText("目录位置");

        jTextField2.setEditable(false);
        jTextField2.setText(new File(homepath+"remoteTemplate").getPath());
        
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/filemanager/folder_open.gif"))); // NOI18N
        jButton4.setText("打开文件夹");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        
        jButton5.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/filemanager/delfile.gif"))); // NOI18N
        jButton5.setText("清理文件夹");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        
        jButton6.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/filemanager/sycme.gif"))); // NOI18N
        jButton6.setText("与服务器同步");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        
        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .add(jButton6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton5)
                .add(7, 7, 7))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton4)
                    .add(jButton5)
                    .add(jButton6))
                .addContainerGap())
        );

        jLabel3.setText("本地报表文件存储路径");

        jButton3.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/filemanager/folder_open.gif"))); // NOI18N
        jButton3.setText("打开文件夹");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        
        jTextField1.setEditable(false);
        jTextField1.setText(new File(System.getProperty("user.home")+File.separator+".ireport").getPath());
        
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("lib文件目录"));

        jLabel5.setText("目录位置");

        jTextField4.setEditable(false);
        jTextField4.setText(new File(homepath+"lib").getPath());
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/filemanager/folder_open.gif"))); // NOI18N
        jButton7.setText("打开文件夹");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        
        jButton8.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/filemanager/delfile.gif"))); // NOI18N
        jButton8.setText("清理文件夹");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        
        
        jButton9.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/filemanager/sycme.gif"))); // NOI18N
        jButton9.setText("与服务器同步");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        
        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .add(jButton9)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton8)
                .add(7, 7, 7))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton7)
                    .add(jButton8)
                    .add(jButton9))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("插件目录"));

        jLabel6.setText("目录位置");

        jTextField5.setEditable(false);
        jTextField5.setText(new File(homepath+"remoteplugins").getPath());
        
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/filemanager/folder_open.gif"))); // NOI18N
        jButton10.setText("打开文件夹");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });
        
        
        jButton11.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/filemanager/delfile.gif"))); // NOI18N
        jButton11.setText("清理文件夹");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });
        
        jButton12.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/filemanager/sycme.gif"))); // NOI18N
        jButton12.setText("与服务器同步");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });
        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .add(jButton12)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton10)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton11)
                .add(7, 7, 7))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(jTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton10)
                    .add(jButton11)
                    .add(jButton12))
                .addContainerGap())
        );

        jButton13.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/filemanager/sycall.gif"))); // NOI18N
        jButton13.setText("同步所有");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });
        jButton14.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/filemanager/sycallfile.gif"))); // NOI18N
        jButton14.setText("清除所有");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });
        jButton15.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/filemanager/cancle.png"))); // NOI18N
        jButton15.setText("关闭");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createSequentialGroup()
                            .add(jLabel3)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jButton3)
                            .add(24, 24, 24))
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jButton13)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton14)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton15)
                        .add(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton13)
                    .add(jButton14)
                    .add(jButton15))
                .addContainerGap())
        );
        this.setTitle("文件夹资源管理");
        pack();
    }// </editor-fold>

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           
    
    
    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here: 1 1
    	IreportUtil.executeDosCommand("explorer "+jTextField1.getText());
    	
    }

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:21
    	IreportUtil.executeDosCommand("explorer "+jTextField3.getText());
    }

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:22
    	List<File> list = IreportUtil.deleteAllFileByFolder(jTextField3.getText());
    	if(list!=null && list.size()!=0){
    		String message = "以下文件删除失败,其他文件删除成功\n";
    		for (int i = 0; i < list.size(); i++) {
    			message +=list.get(i).getName()+"\n";
			}
    		DialogFactory.showErrorMessageDialog(this, message, "文件删除失败");
    	}else{
    		AddedOperator.log("成功清理文件夹所有文件"+jTextField3.getText(),IreportConstant.RIGHT_);
    	}
    }

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:31
    	AddedOperator.getInstance().incrementAddFile(3);
    	
    }

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:32
    	IreportUtil.executeDosCommand("explorer "+jTextField2.getText());
    }

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:33
    	List<File> list = IreportUtil.deleteAllFileByFolder(jTextField2.getText());
    	if(list!=null && list.size()!=0){
    		String message = "以下文件删除失败,其他文件删除成功\n";
    		for (int i = 0; i < list.size(); i++) {
    			message +=list.get(i).getName()+"\n";
			}
    		DialogFactory.showErrorMessageDialog(this, message, "文件删除失败");
    	}else{
    		AddedOperator.log("成功清理文件夹所有文件"+jTextField2.getText(),IreportConstant.RIGHT_);
    	}
    }

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:41
    	AddedOperator.getInstance().incrementAddFile(1);
    }

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:42
    	IreportUtil.executeDosCommand("explorer "+jTextField4.getText());
    	
    }

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:43
    	List<File> list = IreportUtil.deleteAllFileByFolder(jTextField4.getText());
    	if(list!=null && list.size()!=0){
    		String message = "以下文件删除失败,其他文件删除成功\n";
    		for (int i = 0; i < list.size(); i++) {
    			message +=list.get(i).getName()+"\n";
			}
    		DialogFactory.showErrorMessageDialog(this, message, "文件删除失败");
    	}else{
    		AddedOperator.log("成功清理文件夹所有文件"+jTextField4.getText(),IreportConstant.RIGHT_);
    	}
    }

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:51
    	AddedOperator.getInstance().incrementAddFile(2);
    }

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:52
    	IreportUtil.executeDosCommand("explorer "+jTextField5.getText());
    }

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:53
    	List<File> list = IreportUtil.deleteAllFileByFolder(jTextField5.getText());
    	if(list!=null && list.size()!=0){
    		String message = "以下文件删除失败,其他文件删除成功\n";
    		for (int i = 0; i < list.size(); i++) {
    			message +=list.get(i).getName()+"\n";
			}
    		DialogFactory.showErrorMessageDialog(this, message, "文件删除失败");
    	}else{
    		AddedOperator.log("成功清理文件夹所有文件"+jTextField5.getText(),IreportConstant.RIGHT_);
    	}
    }

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:61
    	AddedOperator.getInstance().incrementAddFile(1);
    	AddedOperator.getInstance().incrementAddFile(2);
    	AddedOperator.getInstance().incrementAddFile(3);
    }

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:62
    	
    	int op = JOptionPane.showConfirmDialog(this, "你确定需要清理所有文件夹吗？");
    	if(op != JOptionPane.OK_OPTION){
    		return;
    	}
    	List<File> list = new ArrayList<File>();
     	List<File> list1 = IreportUtil.deleteAllFileByFolder(jTextField3.getText());
    	List<File> list2 = IreportUtil.deleteAllFileByFolder(jTextField2.getText());
    	List<File> list3 = IreportUtil.deleteAllFileByFolder(jTextField4.getText());
    	List<File> list4 = IreportUtil.deleteAllFileByFolder(jTextField5.getText());
    	list.addAll(list1);
    	list.addAll(list2);
    	list.addAll(list3);
    	list.addAll(list4);
    	if(list!=null && list.size()!=0){
    		String message = "以下文件删除失败,其他文件删除成功\n";
    		for (int i = 0; i < list.size(); i++) {
    			message +=list.get(i).getPath()+"\n";
			}
    		DialogFactory.showErrorMessageDialog(this, message, "文件删除失败");
    	}else{
    		AddedOperator.log("成功清理所有文件夹",IreportConstant.RIGHT_);
    	}
    	
    }

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:63
    	this.setVisible(false);
    	this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ResourceManager dialog = new ResourceManager(MainFrame.getMainInstance(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
               
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration
    
}
