/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_chinacreator_ireport_PrinterCheck */

#ifndef _Included_com_chinacreator_ireport_PrinterCheck
#define _Included_com_chinacreator_ireport_PrinterCheck
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_chinacreator_ireport_PrinterCheck
 * Method:    chekcInstall
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_chinacreator_ireport_PrinterCheck_chekcInstall
  (JNIEnv *, jobject);

/*
 * Class:     com_chinacreator_ireport_PrinterCheck
 * Method:    showInstall
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_chinacreator_ireport_PrinterCheck_showInstall
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
