/*
 * ClassMethodDialog.java
 *
 * Created on 2009年10月23日, 上午11:20
 */

package com.chinacreator.ireport.javabeandatasource;

import javax.swing.ListSelectionModel;

import com.chinacreator.ireport.IreportUtil;
import com.chinacreator.ireport.component.DialogFactory;
import com.chinacreator.ireport.rmi.IreportRmiClient;

/**
 * 
 * @author Administrator
 */
public class ClassMethodDialog extends javax.swing.JDialog {

	/** Creates new form ClassMethodDialog */
	public ClassMethodDialog jb = null;
	public JavaBeanRemoteDataSourceConnectionEditor jbeditor = null;

	public ClassMethodDialog(JavaBeanRemoteDataSourceConnectionEditor je,
			java.awt.Dialog parent, boolean modal) {
		super(parent, modal);
		jb = this;
		jbeditor = je;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jScrollPane1 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		jLabel3 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField1.setEditable(false);
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		jLabel1.setText("类名");

		jLabel2.setText(jbeditor.jTextFieldJBSetFactoryClass.getText());

		jScrollPane1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("该类所拥有的方法列表"));

		initJList();

		jList1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		
		jList1
				.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
					public void valueChanged(
							javax.swing.event.ListSelectionEvent evt) {
						jList1ValueChanged(evt);
					}
				});
		jScrollPane1.setViewportView(jList1);

		jLabel3.setText("方法名");

		jButton1.setText("关闭");
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton1MouseClicked(evt);
			}
		});

		jButton2.setText("确定");
		jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton2MouseClicked(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				jPanel1Layout.createSequentialGroup().add(jLabel1,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED).add(
								jLabel2,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								452, Short.MAX_VALUE)).add(jSeparator1,
				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 503,
				Short.MAX_VALUE).add(
				jPanel1Layout.createSequentialGroup().add(jLabel3,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED).add(
								jTextField1,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								446, Short.MAX_VALUE)).add(
				org.jdesktop.layout.GroupLayout.TRAILING,
				jPanel1Layout.createSequentialGroup().add(371, 371, 371).add(
						jButton2).add(18, 18, 18).add(jButton1)).add(
				jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
				503, Short.MAX_VALUE));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								jPanel1Layout
										.createSequentialGroup()
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel1).add(
																jLabel2))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jSeparator1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												jScrollPane1,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												304,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jLabel3)
														.add(
																jTextField1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.add(
												jPanel1Layout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(jButton1).add(
																jButton2))));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				org.jdesktop.layout.GroupLayout.TRAILING,
				layout.createSequentialGroup().addContainerGap().add(jPanel1,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().addContainerGap().add(jPanel1,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE).addContainerGap()));

		pack();
	}// </editor-fold>

	private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {
		String s = (String) jList1.getSelectedValue();
		if(!IreportUtil.isBlank(s)){
			jTextField1.setText(s);
		}
	}

	private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:确定
		String method = jTextField1.getText();
		
		if(!IreportUtil.isBlank(method)){
			jbeditor.jTextFieldJBSetMethodToCall.setText(method);
		}else{
			DialogFactory.showErrorMessageDialog(this, "未选择方法名", "错误");
			return;
		}
		this.dispose();
	}

	private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:取消
		this.dispose();
	}

	private void initJList() {
		try {

			String classname = jbeditor.jTextFieldJBSetFactoryClass.getText();
			if (!IreportUtil.isBlank(classname)) {

				IreportRmiClient.getInstance();
				final String[] ms = IreportRmiClient.rmiInterfactRemote
						.searchClassMethods(classname);
				if (ms == null || ms.length == 0) {
					jList1.setModel(new javax.swing.AbstractListModel() {
						public int getSize() {
							return 0;
						}

						public Object getElementAt(int i) {
							return null;
						}
					});

				} else {
					jList1.setModel(new javax.swing.AbstractListModel() {
						public int getSize() {
							return ms.length;
						}

						public Object getElementAt(int i) {
							return ms[i];
						}
					});
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
			jList1.setModel(new javax.swing.AbstractListModel() {
				public int getSize() {
					return 0;
				}

				public Object getElementAt(int i) {
					return null;
				}
			});
		}
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JList jList1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration

}
