create table TD_REPORT_LOCK(
LOCK_ID VARCHAR2(30) PRIMARY KEY,
REP_ID VARCHAR2(30),
OPEN_TIME DATE,
OPEN_USER VARCHAR2(30),
REP_TYPE VARCHAR2(2),
STATUES VARCHAR2(2),
REP_REF_FILE VARCHAR2(100),
TIME_OUT_TIME DATE,
OPEN_USER_IP VARCHAR2(30),
REP_NAME VARCHAR2(50)
)