/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PrinterCheck */

#ifndef _Included_PrinterCheck
#define _Included_PrinterCheck
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PrinterCheck
 * Method:    chekcInstall
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_PrinterCheck_chekcInstall
  (JNIEnv *, jobject);

/*
 * Class:     PrinterCheck
 * Method:    getWindowHandle
 * Signature: (Ljava/awt/Component;)I
 */
JNIEXPORT jint JNICALL Java_PrinterCheck_getWindowHandle
  (JNIEnv *, jobject, jobject);

/*
 * Class:     PrinterCheck
 * Method:    showInstall
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_PrinterCheck_showInstall
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
