/*
 * LockDialog.java
 *
 * Created on 2009年9月29日, 上午10:56
 */

package it.businesslogic.ireport.plugin.collectionfactory;

import it.businesslogic.ireport.util.Misc;

import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;

import javax.swing.JTable;
import javax.swing.JToolTip;
import javax.swing.ListSelectionModel;
import javax.swing.table.AbstractTableModel;

import com.chinacreator.ireport.AddedOperator;
import com.chinacreator.ireport.IreportConstant;
import com.chinacreator.ireport.IreportUtil;
import com.chinacreator.ireport.component.DialogFactory;
import com.chinacreator.ireport.rmi.IreportRmiClient;
import com.chinacreator.ireport.rmi.PageInfo;
import com.chinacreator.ireport.rmi.ReportDatasourceBean;
import com.tip.MultiLineToolTip;

/**
 * 
 * @author Administrator
 */
public class CollectionFactoryDialog extends javax.swing.JDialog {

	/** Creates new form LockDialog */
	
	private int currentPage = 1;
	private int maxPage = 1;
	
	private int row;
    private int column;

	
	public static CollectionFactoryDialog cfd = null;
	public CollectionFactoryDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        cfd = this;
        initComponents();
        this.setTitle("服务器端javabean数据源配置");
        //不能重新排序各列
        jTable1.getTableHeader().setReorderingAllowed(false);

        jTable1.getColumnModel().getColumn(1).setMaxWidth(600);
        //jTable1.getColumnModel().getColumn(2).setMinWidth(100);
        
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
        
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
       
        jTable1.addMouseListener(
        new MouseAdapter(){
        	
        	public void mouseClicked(MouseEvent e) {
        		if(e.getClickCount() == 2){
        			doShowClassM();
        		}
        	}
        }		
        );	
        
        
        jTable1.addMouseMotionListener(new MouseMotionListener() {

            public void mouseDragged(MouseEvent e) {

            }

            public void mouseMoved(MouseEvent e) {

                Point point = e.getPoint();

                int x = jTable1.rowAtPoint(point);

                int y = jTable1.columnAtPoint(point);

                if (x != row || y != column) {

                    row = x;

                    column = y;

                }
               
                Object tip = jTable1.getValueAt(row, 1);
                Object tip1 = jTable1.getValueAt(row, 2);
                if (tip != null) {
                    jTable1.setToolTipText("类名:"+tip.toString()+"\n"+"方法名:"+tip1);
                }

            }

        });

    }

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	  private void initComponents() {

	        jPanel1 = new javax.swing.JPanel();
	        jPanel2 = new javax.swing.JPanel();
	        jLabel1 = new javax.swing.JLabel();
	        jTextField1 = new javax.swing.JTextField();
	        jButton1 = new javax.swing.JButton();
	        jButton3 = new javax.swing.JButton();
	        jPanel3 = new javax.swing.JPanel();
	        jButton4 = new javax.swing.JButton();
	        jButton5 = new javax.swing.JButton();
	        jTextField2 = new javax.swing.JTextField();
	        jButton6 = new javax.swing.JButton();
	        jButton7 = new javax.swing.JButton();
	        jButton8 = new javax.swing.JButton();
	        jLabel2 = new javax.swing.JLabel();
	        jPanel5 = new javax.swing.JPanel();
	        jButton2 = new javax.swing.JButton();
	        jPanel4 = new javax.swing.JPanel();
	        jScrollPane1 = new javax.swing.JScrollPane();
	        jTable1 = new javax.swing.JTable(){
	        	public JToolTip createToolTip() {
					MultiLineToolTip tip = new MultiLineToolTip();
					tip.setComponent(this);
					return tip;
				}
	        };

	        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

	        jPanel1.setLayout(new java.awt.BorderLayout());

	        jPanel2.setPreferredSize(new java.awt.Dimension(50, 32));

	        jLabel1.setText("服务器javabean数据源ID");

	        jTextField1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField1ActionPerformed(evt);
	            }
	        });

	        jButton1.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/lockmanager/search_1.gif"))); // NOI18N
			jButton1.setText("搜索");
	        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                jButton1MouseClicked(evt);
	            }
	        });
	        
	        jButton2.setText("添加");
	        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                jButton2MouseClicked(evt);
	            }
	        });
	        
	        jButton3.setText("修改");
	        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                jButton3MouseClicked(evt);
	            }
	        });

	        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
	        jPanel2.setLayout(jPanel2Layout);
	        jPanel2Layout.setHorizontalGroup(
	            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
	                .addContainerGap()
	                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	                .add(jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
	                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	                .add(jButton1)
	                .add(18, 18, 18)
	                .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap())
	        );
	        jPanel2Layout.setVerticalGroup(
	            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	            .add(jPanel2Layout.createSequentialGroup()
	                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
	                    .add(jButton1)
	                    .add(jButton3)
	                    .add(jLabel1)
	                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
	                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );

	        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

	        jPanel3.setPreferredSize(new java.awt.Dimension(100, 35));

	        jButton4.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/lockmanager/page-first.gif"))); // NOI18N
	        jButton4.setToolTipText("首页");
	        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
	        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                jButton4MouseClicked(evt);
	            }
	        });

	        jButton5.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/lockmanager/page-prev.gif"))); // NOI18N
			jButton5.setToolTipText("上页");
	        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
	        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                jButton5MouseClicked(evt);
	            }
	        });

	        jTextField2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jTextField2ActionPerformed(evt);
	            }
	        });

	        jButton6.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/lockmanager/page-next.gif"))); // NOI18N
			 jButton6.setToolTipText("下页");
	        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
	        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                jButton6MouseClicked(evt);
	            }
	        });

	        jButton7.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/lockmanager/page-last.gif"))); // NOI18N
			 jButton7.setToolTipText("尾页");
	        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
	        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                jButton7MouseClicked(evt);
	            }
	        });

	        jButton8.setIcon(new javax.swing.ImageIcon(this.getClass().getResource("/it/businesslogic/ireport/plugin/lockmanager/refresh.gif"))); // NOI18N
			jButton8.setToolTipText("刷新");
	        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
	        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
	            public void mouseClicked(java.awt.event.MouseEvent evt) {
	                jButton8MouseClicked(evt);
	            }
	        });

	        jLabel2.setText("显示第1页，共2页");

	        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
	        jPanel3.setLayout(jPanel3Layout);
	        jPanel3.setLayout(jPanel3Layout);
	        jPanel3Layout.setHorizontalGroup(
	            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createSequentialGroup()
	                .addContainerGap()
	                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 322, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 71, Short.MAX_VALUE)
	                .add(jButton2)
	                .add(36, 36, 36)
	                .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	                .add(jButton5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	                .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	                .add(jButton6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	                .add(jButton7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	                .add(jButton8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap())
	        );
	        jPanel3Layout.setVerticalGroup(
	            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	            .add(jPanel3Layout.createSequentialGroup()
	                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
	                        .add(jPanel3Layout.createSequentialGroup()
	                            .addContainerGap()
	                            .add(jLabel2))
	                        .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	                            .add(jTextField2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
	                            .add(jButton6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
	                            .add(jButton7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
	                            .add(jPanel3Layout.createSequentialGroup()
	                                .add(1, 1, 1)
	                                .add(jButton8))
	                            .add(jButton5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
	                            .add(jButton4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)))
	                    .add(jButton2))
	                .addContainerGap())
	        );
	        
	        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_END);

	        jPanel5.setPreferredSize(new java.awt.Dimension(0, 100));

	        org.jdesktop.layout.GroupLayout jPanel5Layout = new org.jdesktop.layout.GroupLayout(jPanel5);
	        jPanel5.setLayout(jPanel5Layout);
	        jPanel5Layout.setHorizontalGroup(
	            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	            .add(0, 0, Short.MAX_VALUE)
	        );
	        jPanel5Layout.setVerticalGroup(
	            jPanel5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	            .add(0, 372, Short.MAX_VALUE)
	        );

	        jPanel1.add(jPanel5, java.awt.BorderLayout.LINE_END);
	       
	        jTable1.setModel(new MyTableModel(null,1));
	        
	        jScrollPane1.setViewportView(jTable1);

	        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
	        jPanel4.setLayout(jPanel4Layout);
	        jPanel4Layout.setHorizontalGroup(
	            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
	        );
	        jPanel4Layout.setVerticalGroup(
	            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
	        );

	        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

	        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
	        );

	        pack();
	    }// </editor-fold>
	
	  
	public void jButton2MouseClicked(MouseEvent evt) {
		//直接添加
		AddCollection dialog = new AddCollection(this, true);
		Misc.centerFrame(dialog);
		dialog.setTitle("为报表添加javabean数据源");
		dialog.setVisible(true);
	}

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {
		String searchStr = jTextField1.getText();
		jTable1.setModel(new MyTableModel(searchStr,1));
		
		resetColumn();
	}

	private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {
		if(maxPage<=0 || currentPage<=1){
			return;
		}
		
		String searchStr = jTextField1.getText();
		jTable1.setModel(new MyTableModel(searchStr,currentPage-1));
		
		resetColumn();
		
		
	}

	private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {
		if(maxPage<=0 || currentPage<=1){
			return;
		}
		
		if(currentPage == maxPage){
			return;
		}
		
		
		String searchStr = jTextField1.getText();
		jTable1.setModel(new MyTableModel(searchStr,currentPage+1));
		
		resetColumn();
	}

	private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		if(currentPage == maxPage){
			return;
		}
		String searchStr = jTextField1.getText();
		jTable1.setModel(new MyTableModel(searchStr,maxPage));
		
		resetColumn();
	}

	private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		//System.out.print("刷新");
		doRefresh();
		
	}

	public void doRefresh(){
		String searchStr = jTextField1.getText();
		jTable1.setModel(new MyTableModel(searchStr,currentPage));
		resetColumn();
	}
	
	public String getCurrendSelectID(){
		int selectRow = jTable1.getSelectedRow();
		if(selectRow==-1){
			return null;
		}
		
		return (String) jTable1.getModel().getValueAt(selectRow,0);
	}
	
	public String getCurrendSelectClassName(){
		int selectRow = jTable1.getSelectedRow();
		if(selectRow==-1){
			return null;
		}
		
		return (String) jTable1.getModel().getValueAt(selectRow,1);
	}
	
	public String getCurrendSelectMethod(){
		int selectRow = jTable1.getSelectedRow();
		if(selectRow==-1){
			return null;
		}
		
		return (String) jTable1.getModel().getValueAt(selectRow,2);
	}
	private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
		//System.out.print("搜索");
		String searchStr = jTextField1.getText();
		jTable1.setModel(new MyTableModel(searchStr,1));
		resetColumn();
		
	}

	private void doShowClassM(){
		int selectRow = jTable1.getSelectedRow();
		
		if(selectRow==-1){
			DialogFactory.showErrorMessageDialog(this, "你未选择行", "错误");
			return;
		}
		
		ServerJavaBeanDatasourceSet s = new ServerJavaBeanDatasourceSet(this,true);
		Misc.centerFrame(s);
		s.setVisible(true);
	}

	private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {
		//System.out.print("修改");
		try {
			
			doShowClassM();
			
		/*	String id = (String) jTable1.getModel().getValueAt(selectRow,1);
			String classname = (String) jTable1.getModel().getValueAt(selectRow,2);
			String method = (String) jTable1.getModel().getValueAt(selectRow,3);
			
			
			IreportRmiClient.getInstance();
			//修改数据库
			
			ReportDatasourceBean rb = new ReportDatasourceBean();
			rb.setBean_report_id(id);
			rb.setClass_name(classname);
			rb.setMethod_name(method);
			IreportRmiClient.rmiInterfactRemote.updateJavaBeanDataSourceRecord(rb);*/
			
			
		} catch (Exception e) {
			AddedOperator.log("修改javabean数据源信息错误:"+e.getMessage(), IreportConstant.ERROR_);
			DialogFactory.showErrorMessageDialog(this, "修改javabean数据源信息错误:"+e.getMessage(), "错误");
		}
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JScrollPane jScrollPane1;
	public javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;

	// End of variables declaration

	class MyTableModel extends AbstractTableModel {
		private Object[][] data = new Object[][] {};

		public MyTableModel(String searchStr,int pageindex) {
			
			if(pageindex<=0){
				pageindex = 1; 
			}
			PageInfo pg = null;
			try {
				 pg = IreportUtil.getCollectionsList(searchStr, pageindex,
						IreportConstant.DEFAULT_PAGE_SIZE);
			} catch (Exception e) {
				
				DialogFactory.showErrorMessageDialog(cfd, "在获得服务器选定数据时出现错误，请检测连接是否正常", "错误");
				AddedOperator.log("在获得服务器选定数据时出现错误，请检测连接是否正常", IreportConstant.ERROR_);
				pg =null;
				return;
			}
			
			if (pg != null) {
				java.util.List<ReportDatasourceBean> list = pg.getIreports();
				Object[][] mydata = IreportUtil.collectionFactoryToObjectArray(list);
				if (mydata != null && mydata.length != 0) {
					data = mydata;
				}

				jLabel2.setText(pageInfoLable(
						pg == null ? 0 : pg.getShowPage(), pg == null ? 0 : pg
								.getTotalPage()));
				jTextField2.setText((pg == null ? 0 : pg.getShowPage()) + "");
			}
			
			}

		private String[] columnNames = {"报表ID", "工厂类", "方法", 
				"修改时间" };

		public int getColumnCount() {
			return columnNames.length;
		}

		public int getRowCount() {
			return data.length;
		}

		public String getColumnName(int col) {
			return columnNames[col];
		}

		public Object getValueAt(int row, int col) {
			return data[row][col];
		}

		public Class getColumnClass(int c) {
			
			// 实现了如果是boolean自动转成JCheckbox
			/*
			 * 需要自己的celleditor这么麻烦吧。jtable自动支持Jcheckbox，
			 * 只要覆盖tablemodel的getColumnClass返回一个boolean的class，
			 * jtable会自动画一个Jcheckbox给你， 你的value是true还是false直接读table里那个cell的值就可以
			 */
			
			return getValueAt(0, c).getClass();
		}

		/*
		 * Don't need to implement this method unless your table's editable.
		 */
		public boolean isCellEditable(int row, int col) {
			// Note that the data/cell address is constant,
			// no matter where the cell appears onscreen.
		
				return false;
			
		}

		/*
		 * Don't need to implement this method unless your table's data can
		 * change.
		 */
		public void setValueAt(Object value, int row, int col) {
			data[row][col] = value;
			fireTableCellUpdated(row, col);

		}

	}

	private String pageInfoLable(int arg1, int arg2) {
		if (arg2 <= 0) {
			maxPage = 0;
			currentPage = 1;
			return "未找到记录";
		}
		int pages = (int) Math.ceil(new Double(arg2)
				/ new Double(IreportConstant.DEFAULT_PAGE_SIZE));
		
		currentPage = arg1;
		maxPage = pages;
		
		return "显示第" + arg1 + "页，共" + pages + "页，" + arg2 + "条记录";
	}

	
	private void resetColumn(){
		if(jTable1.getColumnModel().getColumnCount()>0){
	        jTable1.getColumnModel().getColumn(1).setMaxWidth(600);
	        jTable1.getColumnModel().getColumn(1).setPreferredWidth(250);
	        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
			}
	}
	}


